### ISSUE TITLE
specyfikacja modeli

### ISSUE THREAD

**Issue by AxeKam333** [HonyTawking/DVD-Rental-Project#2]
...

**Comment by HonyTawking** [comment]
Kaseta
  Id_kasety
  film = foreign_key(id_filmu)
  czy_wypozyczone = bool
  aktualnie_wypozycza = foreign_key(User)

Film
  Id_filmu
  Tytuł filmu
  Rok produkcji

**Comment by HonyTawking** [comment]
Do zrobienia 
1. Routes zmienic
2. Po stronie reacta zmienic odbieranie api
3. Bazy danych dzialaja ale bez usera (django robi permission deny jak sie chce zrobic api z usera)
